services:
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"

    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend

  backend:
    image: mohamed7419/taskmanager-backend
    expose:
      - "5000"

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    restart: on-failure

  db:
    image: postgres:13
    expose: 
      - "5432"
    
    env_file:
      - .env

    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db_data:
